# Generated by Django 4.2.20 on 2025-05-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpl', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
