# Generated by Django 4.2.20 on 2025-05-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpl', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
